#!/usr/bin/python
# -*- coding: utf-8 -*-
"""
Django settings for grafiexpress project.

Generated by 'django-admin startproject' using Django 1.8.14.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1p@z$ky1ym)o+0-&nlwrg6$shj&#f@(l-q4t7kq&5ljh(ea$8r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django_crontab',
    'flat_responsive',
    'flat',
    'dal',
    'dal_select2',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'smart_selects',
    'sistema',
    'funcionarios',
    'clientes',
    'materiales',
    'maquinaria',
    'produccion',
    'proveedores',
    'compras',
    'ventas',
    'empresas',
    'ciudades',
    'depositos',
    'automoviles',
    'bancos',
    'cheques',
    'cobros',
    'pagos',
    'comercial',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'grafiexpress.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(os.path.join(BASE_DIR, 'templates'))],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'grafiexpress.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
"""
password_bbdd = 'postgres'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'grafiexpress',                      
        'USER': 'postgres',
        'PASSWORD': '123',
        'HOST': '127.0.0.1'
    }
}
LOGIN_URL = '/admin/login'

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'es-py'

TIME_ZONE = 'America/Asuncion'

USE_I18N = True

USE_L10N = True

USE_TZ = True

USE_THOUSAND_SEPARATOR = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

BASE_DIR = os.path.dirname(os.path.dirname(__file__))
STATICFILES_DIRS = [os.path.join(os.path.join(BASE_DIR, 'static'))]
STATIC_ROOT = os.path.join(os.path.join(BASE_DIR, 'staticfiles'))
MEDIA_ROOT = BASE_DIR+"/media/"
MEDIA_URL = "/media/"
FILE_UPLOAD_HANDLERS = ("django.core.files.uploadhandler.MemoryFileUploadHandler",
                        "django.core.files.uploadhandler.TemporaryFileUploadHandler")

"""
CRONTAB SECTION


# ┌───────────── min (0 - 59)
# │ ┌────────────── hour (0 - 23)
# │ │ ┌─────────────── day of month (1 - 31)
# │ │ │ ┌──────────────── month (1 - 12)
# │ │ │ │ ┌───────────────── day of week (0 - 6) (0 to 6 are Sunday to
# │ │ │ │ │                  Saturday, or use names; 7 is also Sunday)
# │ │ │ │ │
# │ │ │ │ │
# * * * * *  command to execute

# 1 0 * * * -> Con este formato se ejecutara el comando a las 00:01 hs todos los dias
# 0 20 * * * -> Con este formato se ejecutara el comando a las 20:00 hs todos los dias
# */1 * * * * -> Con este formato se ejecutara el comando cada 1 minuto


"""

CRONTAB_PYTHON_EXECUTABLE ="~/webapps/grafiexpress/bin/python2.7"

CRONTAB_DJANGO_PROJECT_NAME = 'grafiexpress'
CRONTAB_DJANGO_MANAGE_PATH = BASE_DIR+'/manage.py'
CRONTAB_DJANGO_SETTINGS_MODULE =  BASE_DIR+'/grafiexpress/settings.py'

CRONJOBS = [
    ('1 0 * * *', 'empresas.cron.set_vencimiento_timbrado', '>> /tmp/scheduled_job.log'),

]
